language: python
python: 
  - 3.6
install:
  - pip install -r requirements.txt
jobs:  
  include:
    - stage: "lint"
      matrix:
        include:
          - python: 3.6
      env: 
        - TESTING=0 SCRIPT="flake8 && flake8-vyper"
  include:
    - stage: "test"
      matrix:
        include:
          - python: 3.6
      env: 
        - TESTING=1 SCRIPT='sb compile && sb -d test test'
script: $SCRIPT
